<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Deep_learning_heart_disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Heart disease deep learning

In [31]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [32]:
data = {
"cholesterol": [150,160,170,180,190,210,220,240,165,175,200,215,230,250,185,205],
"blood_pressure": [80,82,84,86,90,95,100,105,83,85,92,98,102,108,88,96],
"age": [25,28,30,35,40,45,50,55,29,32,42,47,53,60,38,44],
"heart_disease": [0,0,0,0,1,1,1,1,0,0,1,1,1,1,1,1]
}

In [33]:
df = pd.DataFrame(data)

In [34]:
df.isnull().sum()

cholesterol       0
blood_pressure    0
age               0
heart_disease     0
dtype: int64

In [35]:
df

    cholesterol  blood_pressure  age  heart_disease
0           150              80   25              0
1           160              82   28              0
2           170              84   30              0
3           180              86   35              0
4           190              90   40              1
5           210              95   45              1
6           220             100   50              1
7           240             105   55              1
8           165              83   29              0
9           175              85   32              0
10          200              92   42              1
11          215              98   47              1
12          230             102   53              1
13          250             108   60              1
14          185              88   38              1
15          205              96   44              1

In [36]:
X = df.drop(columns='heart_disease',axis=1)
Y = df['heart_disease']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [37]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [38]:
model = Sequential()
model.add(Dense(16,input_dim=3,activation='relu'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [39]:
model.add(Dense(8,activation='relu'))

In [40]:
model.add(Dense(1,activation='sigmoid'))

In [41]:
model.compile(
    loss='binary_crossentropy',
    optimizer=Adam(learning_rate=0.01),
    metrics=['accuracy']
)

In [42]:
model.fit(X_train,Y_train,epochs=20,batch_size=4)

Epoch 1/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.5833 - loss: 0.6812
Epoch 2/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6667 - loss: 0.6177
Epoch 3/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5696
Epoch 4/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.5343
Epoch 5/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.4883
Epoch 6/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.4587
Epoch 7/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6667 - loss: 0.4292
Epoch 8/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.4047
Epoch 9/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6667 - loss: 0.3817
Epoch 10/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.3674
Epoch 11/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.3506
Epoch 12/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.3383
Epoch 13/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.3277
Epoch 14/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.3178
Epoch 15/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6667 - loss: 0.3053
Epoch 16/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.2932
Epoch 17/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7500 - loss: 0.2853
Epoch 18/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.2771
Epoch 19/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.2658
Epoch 20/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.2575

In [43]:
loss,accuracy = model.evaluate(X_test,Y_test)
print(accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - accuracy: 0.7500 - loss: 0.3534
0.75

In [44]:
new_student = np.array([[240,105,55]])
new_student = scaler.transform(new_student)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [45]:
prediction = model.predict(new_student)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step
[[1.]]

In [46]:
if prediction>0.5:
  print("Heart disease is present")
else:
  print("Heart disease is not present")

Heart disease is present