<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 7 - Migraine symptom Classification

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
pd.set_option('display.max_columns', 99)
pd.set_option('display.max_rows', None)

In [15]:
df = pd.read_csv('migraine_symptom_classification.csv')

In [16]:
df.isnull().sum()

Age            0
Duration       0
Frequency      0
Location       0
Character      0
Intensity      0
Nausea         0
Vomit          0
Phonophobia    0
Photophobia    0
Visual         0
Sensory        0
Dysphasia      0
Dysarthria     0
Vertigo        0
Tinnitus       0
Hypoacusis     0
Diplopia       0
Defect         0
Ataxia         0
Conscience     0
Paresthesia    0
DPF            0
Type           0
dtype: int64

In [17]:
le = LabelEncoder()
df['Type'] = le.fit_transform(df['Type'])

In [18]:
df

,Age,Duration,Frequency,Location,Character,Intensity,Nausea,Vomit,Phonophobia,Photophobia,Visual,Sensory,Dysphasia,Dysarthria,Vertigo,Tinnitus,Hypoacusis,Diplopia,Defect,Ataxia,Conscience,Paresthesia,DPF,Type
0,30,1,5,1,1,2,1,0,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,5
1,50,3,5,1,1,3,1,1,1,1,2,1,0,0,1,0,0,0,0,0,0,0,0,5
2,53,2,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
3,45,3,5,1,1,3,1,0,1,1,2,2,0,0,1,0,0,0,0,0,0,0,0,5
4,53,1,1,1,1,2,1,0,1,1,4,0,0,0,0,0,0,0,0,0,0,0,1,5
5,49,1,1,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
6,27,1,5,1,1,3,1,0,1,1,2,0,0,0,1,1,0,0,0,0,0,0,0,0
7,24,1,1,1,1,2,1,0,1,1,2,2,0,0,1,0,0,0,0,0,0,0,1,5
8,50,1,5,1,1,2,1,1,1,1,2,2,0,0,1,0,0,0,0,0,0,0,1,5
9,23,1,1,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
10,48,1,2,1,1,3,1,1,1,1,3,2,0,0,0,0,0,0,0,0,0,0,0,5
11,51,3,1,1,1,3,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,1,5
12,49,2,5,1,1,3,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,5
13,34,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
14,20,3,5,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
15,53,3,5,1,1,3,1,0,1,1,2,0,0,0,1,0,0,0,0,0,0,0,1,5
16,40,3,1,1,1,3,1,0,1,1,4,0,0,0,1,0,0,0,0,0,0,0,1,5
17,56,1,1,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
18,44,3,5,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
19,20,3,8,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
20,46,1,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
21,25,3,7,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
22,38,1,5,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
23,35,2,5,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
24,17,1,6,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
25,36,2,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
26,31,1,7,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
27,67,3,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
28,17,1,5,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
29,46,1,5,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
30,51,3,7,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
31,17,3,6,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
32,22,3,6,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
33,48,2,4,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
34,22,2,3,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
35,68,2,3,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
36,43,3,5,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
37,17,2,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
38,34,2,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
39,41,3,7,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
40,37,1,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
41,26,2,3,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
42,24,1,4,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
43,50,2,4,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
44,31,2,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
45,36,3,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
46,54,1,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
47,27,2,6,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
48,38,1,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
49,35,1,6,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
50,22,3,5,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
51,16,3,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
52,38,3,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
53,33,1,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
54,40,2,4,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
55,22,2,7,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
56,35,2,5,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
57,17,3,4,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
58,35,1,4,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
59,41,1,5,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
60,70,3,5,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2
61,17,1,5,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
62,28,3,5,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
63,29,1,3,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
64,54,1,1,1,1,3,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,1,5
65,40,2,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
66,46,1,1,1,1,3,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,5
67,69,1,5,1,1,3,1,0,1,1,1,2,0,0,0,0,0,0,0,0,0,0,1,5
68,33,2,5,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
69,50,3,1,1,1,2,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,1,5
70,30,3,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
71,17,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
72,22,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
73,16,1,2,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
74,31,1,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
75,30,1,3,1,1,3,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,5
76,16,2,4,1,1,2,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,1,5
77,16,3,2,1,1,2,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,0,5
78,49,1,4,1,1,2,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,1,5
79,41,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
80,21,2,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
81,33,1,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
82,30,1,1,1,1,2,1,1,1,1,0,2,0,0,0,0,0,0,0,0,0,0,1,5
83,64,1,4,1,1,3,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,5
84,27,1,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
85,17,1,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,5
86,27,2,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
87,48,1,3,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
88,32,1,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
89,24,2,2,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
90,25,1,5,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
91,50,1,5,1,1,2,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,5
92,28,1,5,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
93,52,1,2,1,1,2,1,0,1,1,3,2,0,0,0,0,0,0,0,0,0,0,0,5
94,28,1,5,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
95,35,1,5,1,1,3,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,1,5
96,43,2,5,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
97,51,2,1,1,1,2,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,5
98,28,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
99,22,3,1,1,1,2,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,5
100,47,1,2,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
101,44,1,2,1,1,2,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,5
102,49,2,2,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
103,43,1,4,1,1,2,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,5
104,43,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
105,16,2,4,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
106,21,1,1,1,1,2,1,1,1,1,2,2,0,0,0,0,0,0,0,0,0,0,0,5
107,35,1,1,1,1,2,1,1,1,1,2,1,0,0,0,0,0,0,0,0,0,0,1,5
108,25,2,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
109,39,2,1,1,1,2,1,1,1,1,2,2,0,0,0,0,0,0,0,0,0,0,1,5
110,38,1,4,1,1,2,1,1,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,5
111,35,1,5,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
112,43,3,5,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
113,35,3,5,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
114,28,1,1,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
115,57,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
116,58,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
117,26,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
118,28,1,5,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
119,27,1,5,1,1,2,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,1,5
120,42,1,5,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
121,39,1,1,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
122,23,1,1,1,1,2,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,5
123,77,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
124,28,2,3,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
125,47,1,3,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
126,48,3,3,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
127,52,1,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
128,42,1,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
129,18,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
130,35,1,1,1,1,2,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,5
131,25,1,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
132,45,1,1,1,1,2,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,5
133,17,1,3,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
134,29,1,2,1,1,3,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,0,5
135,26,1,5,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
136,26,1,5,1,1,1,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
137,29,2,1,1,1,2,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,5
138,28,2,1,1,1,2,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,5
139,30,1,5,1,1,3,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,1,5
140,30,1,5,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
141,32,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
142,50,1,1,1,1,3,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,5
143,35,3,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
144,57,1,1,1,1,3,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,5
145,30,1,1,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
146,45,1,3,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
147,18,1,3,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
148,45,1,2,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
149,48,1,2,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,5
150,21,1,2,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
151,29,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
152,43,2,1,1,1,2,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,5
153,25,2,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
154,46,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
155,42,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
156,30,3,4,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
157,16,1,4,1,1,3,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,5
158,34,1,1,1,1,1,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
159,17,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
160,20,1,3,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
161,37,1,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
162,51,1,2,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
163,21,1,2,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
164,31,1,2,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
165,59,1,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
166,54,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
167,34,1,2,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
168,46,3,2,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
169,31,1,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
170,30,1,3,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
171,28,2,4,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
172,26,1,4,1,1,3,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
173,27,1,1,1,1,3,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
174,44,1,1,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
175,26,3,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
176,44,3,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
177,29,1,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
178,54,2,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
179,44,2,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
180,18,2,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,5
181,58,1,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,5
182,24,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
183,50,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
184,36,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
185,47,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
186,29,1,2,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
187,51,1,3,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
188,22,1,3,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
189,27,1,5,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
190,21,1,5,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
191,40,1,5,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
192,46,1,5,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
193,29,1,1,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,5
194,25,2,1,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,5
195,51,1,5,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
196,56,1,5,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
197,18,2,5,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
198,37,2,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
199,29,1,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,5
200,50,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
201,49,1,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
202,55,1,1,1,1,2,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,5
203,29,2,1,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
204,18,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
205,26,3,2,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,5
206,41,3,2,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
207,25,1,3,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
208,54,1,3,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
209,31,1,1,1,1,3,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,5
210,49,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
211,18,2,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
212,22,2,2,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
213,38,1,5,1,1,3,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,5
214,26,1,2,1,1,3,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,1,5
215,48,2,2,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
216,26,3,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
217,19,1,2,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,5
218,19,2,3,1,1,3,1,0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,4
219,25,2,2,1,1,3,1,1,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,4
220,27,2,3,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,1
221,16,2,2,1,1,3,1,1,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,5
222,19,2,3,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
223,21,1,4,1,1,2,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,0,5
224,17,2,2,1,1,3,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,5
225,19,1,2,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
226,22,2,3,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
227,20,1,2,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
228,27,2,3,1,1,3,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,5
229,31,1,1,1,1,2,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,5
230,29,1,3,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
231,25,2,2,1,1,2,1,1,1,1,0,2,0,0,0,0,0,0,0,0,0,0,0,5
232,28,2,2,1,1,3,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,5
233,25,1,2,1,1,2,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
234,21,1,3,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
235,19,2,1,1,1,2,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
236,20,2,4,1,1,2,1,0,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,5
237,35,1,3,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
238,15,2,2,1,1,2,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,5
239,27,1,3,1,1,3,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,5
240,21,2,1,1,1,3,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0,5
241,19,2,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
242,15,2,2,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
243,19,3,1,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
244,47,1,5,1,2,3,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,3
245,21,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
246,17,1,2,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
247,20,1,2,1,1,2,1,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,4
248,35,1,3,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
249,28,1,1,2,2,3,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,3
250,15,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
251,30,1,1,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,3
252,32,2,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
253,26,2,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
254,20,1,4,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
255,28,2,2,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
256,20,2,1,1,1,2,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,5
257,25,3,2,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
258,38,3,1,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
259,35,1,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
260,25,1,1,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
261,15,1,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
262,16,1,1,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
263,22,1,1,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
264,22,3,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
265,43,3,1,1,1,2,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,5
266,20,2,1,1,1,2,1,0,1,1,2,2,1,0,0,0,0,0,0,0,0,0,0,5
267,34,2,1,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
268,41,2,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
269,37,2,1,1,1,2,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,5
270,26,1,1,1,1,3,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,0,5
271,24,3,3,1,1,2,1,0,1,1,4,0,0,0,0,0,0,0,0,0,0,0,0,5
272,21,2,1,1,1,2,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,4
273,38,2,1,1,1,3,1,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0
274,35,1,1,0,0,0,1,1,1,1,3,0,0,0,0,0,0,0,0,0,0,0,0,6
275,22,1,2,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
276,16,1,2,1,1,2,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,5
277,38,1,2,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
278,33,1,2,1,1,3,1,0,1,1,0,2,0,0,0,0,0,0,0,0,0,0,0,5
279,40,2,1,1,1,2,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,5
280,22,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
281,35,1,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
282,17,2,2,1,1,3,1,0,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,5
283,35,2,1,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
284,41,2,3,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
285,28,2,2,1,1,2,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
286,31,2,2,1,1,3,1,0,1,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0
287,36,1,2,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
288,27,1,1,1,1,3,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,5
289,19,1,1,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
290,40,1,1,1,1,3,1,0,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,5
291,33,1,1,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
292,30,1,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
293,17,1,3,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
294,22,1,3,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
295,31,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
296,30,1,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
297,16,1,1,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
298,21,2,1,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
299,33,2,3,1,1,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,5
300,27,2,1,1,1,3,1,0,1,1,2,2,0,0,0,0,0,0,0,0,0,0,0,5
301,17,3,2,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
302,24,1,1,1,1,3,1,0,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,5
303,25,1,2,1,1,3,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
304,35,2,1,1,1,2,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,5
305,28,2,2,1,1,3,1,0,1,1,0,2,0,0,0,0,0,0,0,0,0,0,0,5
306,22,2,1,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
307,20,2,2,1,1,3,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,5
308,28,1,1,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
309,22,3,2,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
310,44,1,1,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
311,35,2,2,1,1,3,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,5
312,25,3,1,1,1,2,1,1,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,5
313,39,3,2,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,5
314,35,3,2,1,1,3,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,0,5
315,18,2,2,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
316,28,3,3,1,1,2,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,0,5
317,26,2,1,1,1,3,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2
318,23,2,1,1,1,2,1,1,1,1,3,0,0,0,0,0,0,0,0,0,0,0,0,5
319,24,1,1,1,1,3,1,0,1,1,0,0,1,0,1,1,0,0,0,0,0,0,1,1
320,19,1,1,1,1,3,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1
321,23,1,1,1,1,3,1,0,1,1,2,0,1,0,0,1,0,0,0,0,1,0,1,1
322,25,1,2,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,1
323,21,2,1,1,1,2,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,1,1
324,17,2,1,1,1,3,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1
325,23,1,1,1,1,3,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0,1,1
326,18,2,5,1,1,2,1,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,1,1
327,20,3,5,1,1,3,1,0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,1,1
328,17,3,1,1,1,3,1,0,1,1,3,0,0,0,1,0,0,0,0,0,0,0,1,1
329,15,1,1,1,1,2,1,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,1,1
330,24,1,1,1,1,2,1,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,1,1
331,21,1,2,1,1,2,1,0,1,1,1,2,0,0,1,0,0,0,0,0,0,0,1,1
332,23,1,1,1,1,3,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,1
333,25,1,2,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1
334,17,3,1,1,1,2,1,0,1,1,2,1,1,0,0,0,0,0,0,0,0,0,1,1
335,25,2,2,1,1,2,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,1,1
336,27,1,1,1,1,3,1,0,1,1,2,0,0,0,1,0,0,0,0,0,0,0,1,1
337,20,2,2,1,1,1,1,0,1,1,2,0,1,0,0,1,0,0,0,0,0,0,0,4
338,28,1,2,1,1,3,1,0,1,1,2,0,0,0,1,0,0,0,0,0,0,0,0,4
339,22,2,1,1,1,1,1,0,1,1,3,0,0,0,1,1,0,0,0,0,0,0,0,4
340,21,1,1,1,1,3,1,1,1,1,2,0,1,0,0,0,0,0,0,0,0,0,0,4
341,24,1,1,1,1,2,1,0,1,1,2,2,1,0,1,1,0,0,0,0,0,0,0,4
342,19,1,2,1,1,2,1,1,1,1,2,2,0,0,1,0,0,0,0,0,0,0,0,4
343,23,1,1,1,1,3,1,1,1,1,2,0,1,0,0,0,0,0,0,0,0,0,0,4
344,19,1,2,1,1,1,1,1,1,1,3,2,0,0,0,1,0,0,0,0,0,0,0,4
345,20,2,1,1,1,1,1,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,4
346,21,2,2,1,1,3,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,4
347,19,1,1,1,1,3,1,0,1,1,1,0,1,0,0,1,0,0,0,0,1,0,1,1
348,20,2,2,1,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1
349,23,2,2,1,1,3,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0,1,1
350,25,2,1,1,1,2,1,0,1,1,2,0,1,0,1,0,0,0,0,0,0,0,1,1
351,17,1,1,1,1,3,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1
352,24,1,1,0,0,0,1,1,1,1,4,2,0,0,1,0,0,0,0,0,0,0,1,6
353,21,1,5,0,0,0,1,0,1,1,3,2,0,0,1,0,0,0,0,0,0,0,1,6
354,23,1,1,0,0,0,1,1,1,1,3,0,0,0,0,0,0,0,0,0,0,0,0,6
355,30,1,2,0,0,0,1,0,1,1,3,2,0,0,0,0,0,0,0,0,0,0,0,6
356,27,3,1,0,0,0,1,1,1,1,3,1,0,0,0,0,0,0,0,0,0,0,1,6
357,25,2,5,0,0,0,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,6
358,17,1,1,0,0,0,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,0,6
359,20,3,5,0,0,0,1,1,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,6
360,19,3,5,0,0,0,1,0,1,1,4,0,0,0,1,1,0,0,0,0,0,0,1,6
361,22,3,1,0,0,0,1,0,1,1,3,0,0,0,1,0,0,0,0,0,0,0,1,6
362,26,1,1,0,0,0,1,1,1,1,4,0,0,0,0,0,0,0,0,0,0,0,1,6
363,24,1,1,0,0,0,1,0,1,1,3,2,0,0,1,0,0,0,0,0,0,0,1,6
364,50,1,5,0,0,0,1,1,1,1,3,2,0,0,1,1,0,0,0,0,0,0,1,6
365,23,1,1,0,0,0,1,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,6
366,35,1,2,0,0,0,1,0,1,1,4,2,0,0,0,1,0,0,0,0,0,0,0,6
367,24,3,1,0,0,0,1,0,1,1,3,1,0,0,0,0,0,0,0,0,0,0,1,6
368,33,2,5,0,0,0,1,0,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,6
369,34,1,1,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,6
370,20,3,5,0,0,0,0,0,1,1,4,1,0,0,0,0,0,0,0,0,0,0,1,6
371,53,3,5,2,2,3,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,3
372,40,3,1,1,1,3,0,0,1,0,3,0,0,0,1,0,0,0,0,0,0,0,1,3
373,30,1,1,2,2,3,1,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,1,3
374,24,1,1,1,1,3,0,0,0,0,1,2,0,0,1,0,0,0,0,0,0,0,1,3

In [19]:
X = df.drop(columns='Type',axis=1)
Y = df['Type']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=42,test_size=0.2)

In [20]:
model = LogisticRegression()
model.fit(X_train,Y_train)
Y_predicted = model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [21]:
print("Accuracy:",accuracy_score(Y_predicted,Y_test))

Accuracy: 0.95

In [22]:
new = [[53,2,1,1,1,2,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0]]
result = model.predict(new)
print('''
0 - Basilar-type aura
1 - Familial hemiplegic migraine
2 - Migraine without aura
3 - Other
4 - Sporadic hemiplegic migraine
5 - Typical aura with migraine
6 - Typical aura without migraine
''')
print("Migraine type for given data :",result)

0 - Basilar-type aura
1 - Familial hemiplegic migraine
2 - Migraine without aura
3 - Other
4 - Sporadic hemiplegic migraine
5 - Typical aura with migraine
6 - Typical aura without migraine

Migraine type for given data : [5]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(