<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 22 - Diamond price prediction regression

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor

df = pd.read_csv("diamonds.csv")
df
df.isnull().sum()

Unnamed: 0    0
carat         0
cut           0
color         0
clarity       0
depth         0
table         0
price         0
x             0
y             0
z             0
dtype: int64

In [2]:
df['price'].fillna(df['price'].mean(),inplace=True)
df['x'].fillna(df['x'].mean(),inplace=True)
df['y'].fillna(df['y'].mean(),inplace=True)
df['z'].fillna(df['z'].mean(),inplace=True)
df

/tmp/ipykernel_1876/757357286.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['price'].fillna(df['price'].mean(),inplace=True)
/tmp/ipykernel_1876/757357286.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['x'].fillna(df['x'].mean(),inplace=True)
/tmp/ipykernel_1876/757357286.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['y'].fillna(df['y'].mean(),inplace=True)
/tmp/ipykernel_1876/757357286.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['z'].fillna(df['z'].mean(),inplace=True)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [3]:
le = LabelEncoder()
df["cut"] = le.fit_transform(df["cut"])
df["color"] = le.fit_transform(df["color"])
df["clarity"] = le.fit_transform(df["clarity"])
df.head(50)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,2,1,3,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,3,1,2,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,1,1,4,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,3,5,5,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,1,6,3,63.3,58.0,335,4.34,4.35,2.75
5,6,0.24,4,6,7,62.8,57.0,336,3.94,3.96,2.48
6,7,0.24,4,5,6,62.3,57.0,336,3.95,3.98,2.47
7,8,0.26,4,4,2,61.9,55.0,337,4.07,4.11,2.53
8,9,0.22,0,1,5,65.1,61.0,337,3.87,3.78,2.49
9,10,0.23,4,4,4,59.4,61.0,338,4.00,4.05,2.39
10,11,0.30,1,6,2,64.0,55.0,339,4.25,4.28,2.73
11,12,0.23,2,6,4,62.8,56.0,340,3.93,3.90,2.46
12,13,0.22,3,2,2,60.4,61.0,342,3.88,3.84,2.33
13,14,0.31,2,6,3,62.2,54.0,344,4.35,4.37,2.71
14,15,0.20,3,1,3,60.2,62.0,345,3.79,3.75,2.27
15,16,0.32,3,1,0,60.9,58.0,345,4.38,4.42,2.68
16,17,0.30,2,5,3,62.0,54.0,348,4.31,4.34,2.68
17,18,0.30,1,6,2,63.4,54.0,351,4.23,4.29,2.70
18,19,0.30,1,6,2,63.8,56.0,351,4.23,4.26,2.71
19,20,0.30,4,6,2,62.7,59.0,351,4.21,4.27,2.66
20,21,0.30,1,5,3,63.3,56.0,351,4.26,4.30,2.71
21,22,0.23,4,1,5,63.8,55.0,352,3.85,3.92,2.48
22,23,0.23,4,4,4,61.0,57.0,353,3.94,3.96,2.41
23,24,0.31,4,6,2,59.4,62.0,353,4.39,4.43,2.62
24,25,0.31,4,6,2,58.1,62.0,353,4.44,4.47,2.59
25,26,0.23,4,3,7,60.4,58.0,354,3.97,4.01,2.41
26,27,0.24,3,5,4,62.5,57.0,355,3.97,3.94,2.47
27,28,0.30,4,6,5,62.2,57.0,357,4.28,4.30,2.67
28,29,0.23,4,0,5,60.5,61.0,357,3.96,3.97,2.40
29,30,0.23,4,2,4,60.9,57.0,357,3.96,3.99,2.42
30,31,0.23,4,2,4,60.0,57.0,402,4.00,4.03,2.41
31,32,0.23,4,2,4,59.8,57.0,402,4.04,4.06,2.42
32,33,0.23,4,1,4,60.7,59.0,402,3.97,4.01,2.42
33,34,0.23,4,1,4,59.5,58.0,402,4.01,4.06,2.40
34,35,0.23,4,0,4,61.9,58.0,402,3.92,3.96,2.44
35,36,0.23,1,2,4,58.2,59.0,402,4.06,4.08,2.37
36,37,0.23,1,1,4,64.1,59.0,402,3.83,3.85,2.46
37,38,0.31,1,4,2,64.0,54.0,402,4.29,4.31,2.75
38,39,0.26,4,0,5,60.8,59.0,403,4.13,4.16,2.52
39,40,0.33,2,5,3,61.8,55.0,403,4.49,4.51,2.78
40,41,0.33,2,5,3,61.2,56.0,403,4.49,4.50,2.75
41,42,0.33,2,6,2,61.1,56.0,403,4.49,4.55,2.76
42,43,0.26,1,0,5,65.2,56.0,403,3.99,4.02,2.61
43,44,0.26,1,0,4,58.4,63.0,403,4.19,4.24,2.46
44,45,0.32,1,4,3,63.1,56.0,403,4.34,4.37,2.75
45,46,0.29,3,2,2,62.4,58.0,403,4.24,4.26,2.65
46,47,0.32,4,4,3,61.8,55.0,403,4.35,4.42,2.71
47,48,0.32,1,4,3,63.8,56.0,403,4.36,4.38,2.79
48,49,0.25,4,1,5,63.3,60.0,404,4.00,4.03,2.54
49,50,0.29,4,4,3,60.7,60.0,404,4.33,4.37,2.64

In [4]:
X = df.drop(columns=['price','Unnamed: 0'],axis =1)
Y = df['price']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [5]:
model = DecisionTreeRegressor()
model.fit(X_train,Y_train)
Y_predict = model.predict(X_test)
r2 = r2_score(Y_predict,Y_test)
mse = mean_squared_error(Y_predict,Y_test)
print(r2)
print(mse)

0.9678528415017407
513858.71866889135

In [6]:
new = [[0.32,1,4,3,63.8,56.0,4.36,4.38,2.79]]
prediction = model.predict(new)
print("predicted Diamond price for the given data is :",prediction[0])

predicted Diamond price for the given data is : 403.0

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(