<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 23 - Car price prediction regression

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("ford.csv")
df
df.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [3]:
le = LabelEncoder()
df["model"] = le.fit_transform(df["model"])
df["transmission"] = le.fit_transform(df["transmission"])
df["fuelType"] = le.fit_transform(df["fuelType"])
df["fuelType"] = le.fit_transform(df["fuelType"])
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5,2017,12000,0,15944,4,150,57.7,1.0
1,6,2018,14000,1,9083,4,150,57.7,1.0
2,6,2017,13000,1,12456,4,150,57.7,1.0
3,5,2019,17500,1,10460,4,145,40.3,1.5
4,5,2019,16500,0,1482,4,145,48.7,1.0
...,...,...,...,...,...,...,...,...,...
17961,0,2017,8999,1,16700,4,150,47.1,1.4
17962,0,2014,7499,1,40700,4,30,57.7,1.0
17963,6,2015,9999,1,7010,0,20,67.3,1.6
17964,11,2018,8299,1,5007,4,145,57.7,1.2
17965,23,2015,8299,1,5007,4,22,57.7,1.0

In [4]:
X = df.drop(columns=['year','price'],axis =1)
Y = df['price']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [11]:
model = LinearRegression()
model.fit(X_train,Y_train)
Y_predict = model.predict(X_test)

In [9]:
r2 = r2_score(Y_predict,Y_test)
mse = mean_squared_error(Y_predict,Y_test)
print(r2)
print(mse)

0.8370525177718235
3565128.458183469

In [13]:
new = [[5,0,15944,4,150,57.7,1.0]]
prediction = model.predict(new)
print("Predicted Car price for the given data :",prediction[0])

Predicted Car price for the given data : 11993.89815788754

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(