<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 9 - Rice Classification

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

In [2]:
df = pd.read_csv('riceClassification.csv')

In [3]:
df.isnull().sum()

id                 0
Area               0
MajorAxisLength    0
MinorAxisLength    0
Eccentricity       0
ConvexArea         0
EquivDiameter      0
Extent             0
Perimeter          0
Roundness          0
AspectRation       0
Class              0
dtype: int64

In [4]:
df.tail(n=10)

,id,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,EquivDiameter,Extent,Perimeter,Roundness,AspectRation,Class
18175,18176,9101,183.211434,65.025256,0.934897,9431,107.646426,0.474505,414.047,0.667113,2.817543,0
18176,18177,7595,166.372864,59.045507,0.934905,7734,98.337451,0.482406,371.322,0.692207,2.817706,0
18177,18178,5865,146.173653,51.619196,0.935572,6011,86.414987,0.550188,326.864,0.689833,2.831769,0
18178,18179,6165,149.401504,52.686933,0.935754,6295,88.597527,0.659782,339.234,0.673200,2.835646,0
18179,18180,5757,146.505031,50.650032,0.938337,5859,85.615653,0.475785,326.511,0.678595,2.892496,0
18180,18181,5853,148.624571,51.029281,0.939210,6008,86.326537,0.498594,332.960,0.663444,2.912535,0
18181,18182,7585,169.593996,58.141659,0.939398,7806,98.272692,0.647461,385.506,0.641362,2.916910,0
18182,18183,6365,154.777085,52.908085,0.939760,6531,90.023162,0.561287,342.253,0.682832,2.925396,0
18183,18184,5960,151.397924,51.474600,0.940427,6189,87.112041,0.492399,343.371,0.635227,2.941216,0
18184,18185,6134,153.081981,51.590606,0.941500,6283,88.374495,0.489975,338.613,0.672274,2.967245,0

In [5]:
X = df.drop(columns=['id','Class'],axis=1)
Y = df['Class']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=42,test_size=0.2)

In [6]:
model = SVC(kernel="linear")
model.fit(X_train,Y_train)
Y_predicted = model.predict(X_test)

In [7]:
print('Accuracy:',accuracy_score(Y_predicted,Y_test))

Accuracy: 0.9895518284300248

In [8]:
new = [[9101,183.211434,65.025256,0.934897,9431,107.646426,0.474505,414.047,0.667113,2.817543]]
result = model.predict(new)
print('''
1 - Jasmine,
0 - Gonen
''')
print("Rice class for the given data :",result)

1 - Jasmine,
0 - Gonen

Rice class for the given data : [0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(