<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 3 - Hotel Booking Probability

In [47]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor
pd.set_option('display.max_columns', 99)

In [24]:
df = pd.read_csv('hotel_bookings_updated_2024.csv')

In [25]:
df.isnull().sum()

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              4
babies                                0
meal                                  0
country                             487
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             13191
company                           82960
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
city                                  1
dtype: int64

In [26]:
df['children'] = df['children'].fillna(df['children'].mean())
df['country'] = df['country'].fillna(df['country'].mode()[0])
df['agent'] = df['agent'].fillna(df['agent'].mean())
df['company'] = df['company'].fillna(df['company'].mean())

In [27]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,city
0,Resort Hotel - Chandigarh,0,342,2024,July,30,27,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,107.243534,186.0617,0,Transient,0.00,0,0,Check-Out,2024-07-27 22:16:40.916332324,Chandigarh
1,Resort Hotel - Mumbai,0,737,2024,April,17,28,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,107.243534,186.0617,0,Transient,0.00,0,0,Check-Out,2024-04-28 21:56:21.507509066,Mumbai
2,Resort Hotel - Delhi,0,7,2024,September,37,10,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,107.243534,186.0617,0,Transient,75.00,0,0,Check-Out,2024-09-10 03:46:25.734029096,Delhi
3,Resort Hotel - Kolkata,0,13,2024,August,33,14,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.000000,186.0617,0,Transient,75.00,0,0,Check-Out,2024-08-14 18:07:10.049669568,Kolkata
4,Resort Hotel - Lucknow,0,14,2024,September,37,14,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.000000,186.0617,0,Transient,98.00,0,1,Check-Out,2024-09-14 14:27:32.473846000,Lucknow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88190,City Hotel - Kolkata,0,99,2024,August,35,31,1,3,2,0.0,0,BB,POL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.000000,186.0617,0,Transient,101.58,0,1,Check-Out,2024-08-31 02:48:53.757716372,Kolkata
88191,City Hotel - Bangalore,0,2,2024,July,28,8,1,4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,F,F,0,No Deposit,7.000000,186.0617,0,Transient,162.47,0,2,Check-Out,2024-07-08 17:55:55.575471776,Bangalore
88192,City Hotel - Hyderabad,0,79,2024,April,17,28,1,3,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.000000,186.0617,0,Transient-Party,125.38,0,0,Check-Out,2024-04-28 06:27:26.925596160,Hyderabad
88193,City Hotel - Jaipur,0,4,2024,March,11,17,1,0,1,0.0,0,BB,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.000000,186.0617,0,Transient,125.00,0,1,Check-Out,2024-03-17 05:07:49.158800224,Jaipur
88194,City Hotel - Lucknow,0,47,2024,March,13,28,1,3,2,0.0,0,BB,ARG,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.000000,186.0617,0,Transient,123.96,1,1,Check-Out,2024-03-28 01:45:11.9784,NaN

In [28]:
le = LabelEncoder()

df['hotel'] = le.fit_transform(df['hotel'])
df['arrival_date_month'] = le.fit_transform(df['arrival_date_month'])
df['meal'] = le.fit_transform(df['meal'])
df['country'] = le.fit_transform(df['country'])
df['market_segment'] = le.fit_transform(df['market_segment'])
df['distribution_channel'] = le.fit_transform(df['distribution_channel'])
df['reserved_room_type'] = le.fit_transform(df['reserved_room_type'])
df['assigned_room_type'] = le.fit_transform(df['assigned_room_type'])
df['deposit_type'] = le.fit_transform(df['deposit_type'])
df['customer_type'] = le.fit_transform(df['customer_type'])
df['reservation_status'] = le.fit_transform(df['reservation_status'])
df['city'] = le.fit_transform(df['city'])

In [29]:
df.head(n=15)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,city
0,18,0,342,2024,5,30,27,0,0,2,0.0,0,0,119,3,1,0,0,0,2,2,3,0,107.243534,186.0617,0,2,0.00,0,0,1,2024-07-27 22:16:40.916332324,3
1,28,0,737,2024,0,17,28,0,0,2,0.0,0,0,119,3,1,0,0,0,2,2,4,0,107.243534,186.0617,0,2,0.00,0,0,1,2024-04-28 21:56:21.507509066,13
2,20,0,7,2024,11,37,10,0,1,1,0.0,0,0,51,3,1,0,0,0,0,2,0,0,107.243534,186.0617,0,2,75.00,0,0,1,2024-09-10 03:46:25.734029096,5
3,26,0,13,2024,1,33,14,0,1,1,0.0,0,0,51,2,0,0,0,0,0,0,0,0,304.000000,186.0617,0,2,75.00,0,0,1,2024-08-14 18:07:10.049669568,11
4,27,0,14,2024,11,37,14,0,2,2,0.0,0,0,51,6,3,0,0,0,0,0,0,0,240.000000,186.0617,0,2,98.00,0,1,1,2024-09-14 14:27:32.473846000,12
5,20,0,14,2024,10,43,23,0,2,2,0.0,0,0,51,6,3,0,0,0,0,0,0,0,240.000000,186.0617,0,2,98.00,0,1,1,2024-10-23 04:39:14.025915284,5
6,23,0,0,2024,4,1,7,0,2,2,0.0,0,0,119,3,1,0,0,0,2,2,0,0,107.243534,186.0617,0,2,107.00,0,0,1,2024-01-07 03:46:27.905083382,8
7,15,0,9,2024,1,32,8,0,2,2,0.0,0,1,119,3,1,0,0,0,2,2,0,0,303.000000,186.0617,0,2,103.00,0,1,1,2024-08-08 18:58:03.275678664,0
8,20,1,85,2024,1,34,25,0,3,2,0.0,0,0,119,6,3,0,0,0,0,0,0,0,240.000000,186.0617,0,2,82.00,0,1,0,2024-08-25 06:44:41.071120456,5
9,29,1,75,2024,2,51,18,0,3,2,0.0,0,2,119,5,3,0,0,0,3,3,0,0,15.000000,186.0617,0,2,105.50,0,0,0,2024-12-18 05:00:17.579509000,14
10,19,1,23,2024,1,34,24,0,4,2,0.0,0,0,119,6,3,0,0,0,4,4,0,0,240.000000,186.0617,0,2,123.00,0,0,0,2024-08-24 00:39:41.646550352,4
11,19,0,35,2024,7,13,27,0,4,2,0.0,0,2,119,6,3,0,0,0,3,3,0,0,240.000000,186.0617,0,2,145.00,0,0,1,2024-03-27 17:01:18.730871353,4
12,17,0,68,2024,7,9,2,0,4,2,0.0,0,0,148,6,3,0,0,0,3,4,0,0,240.000000,186.0617,0,2,97.00,0,3,1,2024-03-02 00:36:37.106936150,2
13,27,0,18,2024,6,23,9,0,4,2,1.0,0,2,43,6,3,0,0,0,6,6,1,0,241.000000,186.0617,0,2,154.77,0,1,1,2024-06-09 11:36:00.229166840,12
14,22,0,37,2024,6,24,15,0,4,2,0.0,0,0,119,6,3,0,0,0,4,4,0,0,241.000000,186.0617,0,2,94.71,0,0,1,2024-06-15 23:44:20.657179472,7

In [40]:
X = df.drop(columns=['is_canceled','arrival_date_year','arrival_date_month','reservation_status_date','hotel'],axis=1)
Y = df['is_canceled']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=42,test_size=0.2)

In [41]:
model = DecisionTreeRegressor()
model.fit(X_train,Y_train)
Y_predicted = model.predict(X_test)

In [42]:
r2 = r2_score(Y_predicted,Y_test)
mse = mean_squared_error(Y_predicted,Y_test)
print(r2)
print(mse)

1.0
0.0

In [46]:
new = [[68,9,2,0,4,2,0.0,0,0,148,6,3,0,0,0,3,4,0,0,240.000000,186.0617,0,2,97.00,0,3,1,2]]
result = model.predict(new)
if result >=1:
  print("Hotel booking is confirmed")
else:
  print("Hotel booking is cancelled")

Hotel booking is cancelled

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(