<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 5 - Longevity Regression

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor

In [2]:
df = pd.read_csv('Updated Quality of Life Data.csv')

In [3]:
df.isnull().sum()

id                            0
gender                        0
occupation_type               0
avg_work_hours_per_day        0
avg_rest_hours_per_day        0
avg_sleep_hours_per_day       0
avg_exercise_hours_per_day    0
age_at_death                  0
dtype: int64

In [4]:
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])
df['occupation_type'] = le.fit_transform(df['occupation_type'])
df

,id,gender,occupation_type,avg_work_hours_per_day,avg_rest_hours_per_day,avg_sleep_hours_per_day,avg_exercise_hours_per_day,age_at_death
0,10001,0,12,6.60,10.92,5.38,1.10,88
1,10002,1,9,9.65,7.65,6.31,0.39,76
2,10003,0,7,13.77,1.00,8.02,1.21,78
3,10004,0,5,10.94,5.18,7.59,0.29,74
4,10005,1,3,9.81,5.11,7.38,1.70,78
...,...,...,...,...,...,...,...,...
9995,19996,0,13,8.39,8.12,6.91,0.58,89
9996,19997,1,10,9.58,6.40,6.93,1.09,90
9997,19998,0,1,10.02,4.75,7.55,1.68,89
9998,19999,0,3,7.97,8.07,7.78,0.17,87
9999,20000,0,5,7.73,7.66,7.61,1.00,87

In [5]:
X = df.drop(columns=['id','age_at_death'])
Y = df[['age_at_death']]
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [6]:
model = DecisionTreeRegressor()
model.fit(X_train,Y_train)
Y_predicted = model.predict(X_test)

In [7]:
r2 = r2_score(Y_predicted,Y_test)
mse = mean_squared_error(Y_predicted,Y_test)
print(r2)
print(mse)

0.17056374852746448
131.535

In [8]:
new = [[0,5,7.73,7.66,7.61,1.00]]
result = model.predict(new)
print("Age of death for given data :",result)

Age of death for given data : [87.]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(