<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 10 - Water Quality Classification

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
pd.set_option('display.max_columns', 99)
pd.set_option('display.max_rows', 99)

In [11]:
df = pd.read_csv('waterQuality1.csv')

In [12]:
df.isnull().sum()

aluminium      0
ammonia        3
arsenic        0
barium         0
cadmium        0
chloramine     0
chromium       0
copper         0
flouride       0
bacteria       0
viruses        0
lead           0
nitrates       0
nitrites       0
mercury        0
perchlorate    0
radium         0
selenium       0
silver         0
uranium        0
is_safe        3
dtype: int64

In [13]:
df['ammonia'].fillna(0,inplace=True)
df['is_safe'].fillna(0,inplace=True)

/tmp/ipykernel_799/4172794426.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ammonia'].fillna(0,inplace=True)
/tmp/ipykernel_799/4172794426.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['is_safe'].fillna(0,inplace=True)

In [14]:
df.head(100)

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,viruses,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
0,1.65,9.08,0.04,2.85,0.007,0.35,0.83,0.17,0.05,0.20,0.000,0.054,16.08,1.13,0.007,37.75,6.78,0.08,0.34,0.02,1.0
1,2.32,21.16,0.01,3.31,0.002,5.28,0.68,0.66,0.90,0.65,0.650,0.100,2.01,1.93,0.003,32.26,3.21,0.08,0.27,0.05,1.0
2,1.01,14.02,0.04,0.58,0.008,4.24,0.53,0.02,0.99,0.05,0.003,0.078,14.16,1.11,0.006,50.28,7.07,0.07,0.44,0.01,0.0
3,1.36,11.33,0.04,2.96,0.001,7.23,0.03,1.66,1.08,0.71,0.710,0.016,1.41,1.29,0.004,9.12,1.72,0.02,0.45,0.05,1.0
4,0.92,24.33,0.03,0.20,0.006,2.67,0.69,0.57,0.61,0.13,0.001,0.117,6.74,1.11,0.003,16.90,2.41,0.02,0.06,0.02,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.43,13.55,0.03,3.28,0.001,2.38,0.17,0.25,1.25,0.70,0.700,0.129,15.72,1.81,0.003,10.88,5.41,0.03,0.11,0.07,1.0
96,2.63,19.11,0.02,1.74,0.007,1.89,0.69,0.87,0.69,0.55,0.550,0.153,5.91,1.31,0.007,39.05,4.15,0.01,0.38,0.08,1.0
97,2.85,23.02,0.03,2.24,0.004,0.46,0.02,1.77,0.62,0.14,0.006,0.137,14.86,1.19,0.004,27.85,7.60,0.01,0.45,0.05,0.0
98,0.04,13.18,0.02,2.44,0.001,4.80,0.33,0.73,0.68,0.45,0.006,0.053,17.71,1.73,0.008,58.40,6.60,0.10,0.06,0.04,0.0
99,0.88,11.12,0.04,0.92,0.009,4.59,0.85,1.10,1.48,0.75,0.750,0.147,8.25,1.38,0.007,10.75,1.20,0.02,0.27,0.02,1.0

In [15]:
X = df.drop(columns='is_safe',axis=1)
Y = df['is_safe']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=42,test_size=0.2)

In [16]:
model = DecisionTreeClassifier()
model.fit(X_train,Y_train)
Y_predicted = model.predict(X_test)

In [17]:
print("Accuracy:",accuracy_score(Y_predicted,Y_test))

Accuracy: 0.9575

In [18]:
new = [[0.04,13.18,0.02,2.44,0.001,4.80,0.33,0.73,0.68,0.45,0.006,0.053,17.71,1.73,0.008,58.40,6.60,0.10,0.06,0.04]]
result = model.predict(new)
if result:
  print("Water quality is good")
else:
  print("Water quality is not good")

Water quality is not good

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(