<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 1 - Energy consumption regression

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('test_energy_data.csv')

In [ ]:
df

,Building Type,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Day of Week,Energy Consumption
0,Residential,24563,15,4,28.52,Weekday,2865.57
1,Commercial,27583,56,23,23.07,Weekend,4283.80
2,Commercial,45313,4,44,33.56,Weekday,5067.83
3,Residential,41625,84,17,27.39,Weekend,4624.30
4,Residential,36720,58,47,17.08,Weekday,4820.59
...,...,...,...,...,...,...,...
95,Commercial,1161,81,11,15.45,Weekend,3010.81
96,Residential,37943,50,23,21.73,Weekend,4248.49
97,Commercial,1558,27,29,16.86,Weekend,2843.60
98,Industrial,2145,56,12,11.77,Weekend,3348.39
99,Residential,42414,72,24,29.62,Weekday,4722.59

In [ ]:
df.isnull().sum()

Building Type          0
Square Footage         0
Number of Occupants    0
Appliances Used        0
Average Temperature    0
Day of Week            0
Energy Consumption     0
dtype: int64

In [ ]:
le = LabelEncoder()

In [ ]:
df['Building Type']= le.fit_transform(df['Building Type'])
df['Day of Week']= le.fit_transform(df['Day of Week'])
df

,Building Type,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Day of Week,Energy Consumption
0,2,24563,15,4,28.52,0,2865.57
1,0,27583,56,23,23.07,1,4283.80
2,0,45313,4,44,33.56,0,5067.83
3,2,41625,84,17,27.39,1,4624.30
4,2,36720,58,47,17.08,0,4820.59
...,...,...,...,...,...,...,...
95,0,1161,81,11,15.45,1,3010.81
96,2,37943,50,23,21.73,1,4248.49
97,0,1558,27,29,16.86,1,2843.60
98,1,2145,56,12,11.77,1,3348.39
99,2,42414,72,24,29.62,0,4722.59

In [ ]:
X = df.drop(columns='Energy Consumption',axis=1)
Y = df[['Energy Consumption']]
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X_train,Y_train)
Y_predict = model.predict(X_test)

In [ ]:
r2 = r2_score(Y_predict,Y_test)
mse = mean_squared_error(Y_predict,Y_test)
print(r2)
print(mse)

0.7363884499221537
122899.62182247973

In [ ]:
new = [[2,37943,50,23,21.73,1]]
result = model.predict(new)
print("Energy consumption for given data is :",result)

Energy consumption for given data is : [[4399.83798257]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(