<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 24 - Calory burnt regression

In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor

In [3]:
df2 = pd.read_csv("calories.csv")
df = pd.read_csv("exercise.csv")
df
df.isnull().sum()
df2

        User_ID  Calories
0      14733363     231.0
1      14861698      66.0
2      11179863      26.0
3      16180408      71.0
4      17771927      35.0
...         ...       ...
14995  15644082      45.0
14996  17212577      23.0
14997  17271188      75.0
14998  18643037      11.0
14999  11751526      98.0

[15000 rows x 2 columns]

In [4]:
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])
df

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0      14733363       1   68   190.0    94.0      29.0       105.0       40.8
1      14861698       0   20   166.0    60.0      14.0        94.0       40.3
2      11179863       1   69   179.0    79.0       5.0        88.0       38.7
3      16180408       0   34   179.0    71.0      13.0       100.0       40.5
4      17771927       0   27   154.0    58.0      10.0        81.0       39.8
...         ...     ...  ...     ...     ...       ...         ...        ...
14995  15644082       0   20   193.0    86.0      11.0        92.0       40.4
14996  17212577       0   27   165.0    65.0       6.0        85.0       39.2
14997  17271188       0   43   159.0    58.0      16.0        90.0       40.1
14998  18643037       1   78   193.0    97.0       2.0        84.0       38.3
14999  11751526       1   63   173.0    79.0      18.0        92.0       40.5

[15000 rows x 8 columns]

In [5]:
X = df.drop(columns=['User_ID'],axis =1)
Y = df2['Calories']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)
print(X_train)

       Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
9839        1   37   179.0    77.0       7.0        81.0       39.5
9680        1   23   195.0    87.0      26.0       110.0       40.5
7093        1   33   181.0    77.0      12.0        88.0       40.1
11293       0   66   156.0    54.0       9.0        77.0       39.5
820         0   32   144.0    49.0       5.0        90.0       39.0
...       ...  ...     ...     ...       ...         ...        ...
5191        0   75   148.0    51.0      22.0       104.0       40.6
13418       0   21   172.0    67.0      20.0       104.0       40.7
5390        1   57   189.0    92.0       8.0        90.0       39.5
860         1   35   174.0    76.0      12.0        97.0       40.2
7270        1   26   182.0    86.0      16.0        91.0       40.5

[12000 rows x 7 columns]

In [12]:
model = DecisionTreeRegressor()
model.fit(X_train,Y_train)
Y_predict = model.predict(X_test)

In [8]:
r2 = r2_score(Y_predict,Y_test)
mse = mean_squared_error(Y_predict,Y_test)
print(r2)
print(mse)

0.9931098580435331
27.747

In [13]:
new = [[0,43,159.0,58.0,16.0,90.0,40.1]]
prediction = model.predict(new)
print("Calory burnt for the given data is :",prediction[0])

Calory burnt for the given data is : 75.0

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(