<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 4 - House price prediction Regression

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error

In [2]:
df = pd.read_csv("house_price_regression_dataset.csv")

In [3]:
df

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10,7.014940e+05
996,3179,1,2,1999,2.977123,1,10,6.837232e+05
997,2606,4,2,1962,4.055067,0,2,5.720240e+05
998,4723,5,2,1950,1.930921,0,7,9.648653e+05
999,3268,4,2,1983,3.108790,2,2,7.425993e+05

In [4]:
df.isnull().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

In [5]:
X = df.drop(columns=['House_Price'],axis=1)
Y = df[['House_Price']]
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [6]:
model = LinearRegression()
model.fit(X_train,Y_train)
Y_predict = model.predict(X_test)

In [7]:
r2 = r2_score(Y_predict,Y_test)
mse = mean_squared_error(Y_predict,Y_test)
print(r2)
print(mse)

0.9984045915312583
101434798.50566797

In [8]:
new = [[3671,1,2,2012,4.911960066216673,0,1]]
result=model.predict(new)
print("House price for given data :",result)

House price for given data : [[820716.04706147]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(