<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 25 - Student performance regression

In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor

In [2]:
df = pd.read_csv("StudentPerformanceFactors.csv")
df
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [3]:
le = LabelEncoder()
df["Parental_Involvement"] = le.fit_transform(df["Parental_Involvement"])
df["Access_to_Resources"] = le.fit_transform(df["Access_to_Resources"])
df["Extracurricular_Activities"] = le.fit_transform(df["Extracurricular_Activities"])
df["Motivation_Level"] = le.fit_transform(df["Motivation_Level"])
df["Internet_Access"] = le.fit_transform(df["Internet_Access"])
df["Family_Income"] = le.fit_transform(df["Family_Income"])
df["Teacher_Quality"] = le.fit_transform(df["Teacher_Quality"])
df["School_Type"] = le.fit_transform(df["School_Type"])
df["Peer_Influence"] = le.fit_transform(df["Peer_Influence"])
df["Learning_Disabilities"] = le.fit_transform(df["Learning_Disabilities"])
df["Parental_Education_Level"] = le.fit_transform(df["Parental_Education_Level"])
df["Distance_from_Home"] = le.fit_transform(df["Distance_from_Home"])
df["Gender"] = le.fit_transform(df["Gender"])
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,1,0,0,7,73,1,1,0,1,2,1,2,3,0,1,2,1,67
1,19,64,1,2,0,8,59,1,1,2,2,2,1,0,4,0,0,1,0,61
2,24,98,2,2,1,7,91,2,1,2,2,2,1,1,4,0,2,2,1,74
3,29,89,1,2,1,8,98,2,1,1,2,2,1,0,4,0,1,1,1,71
4,19,92,2,2,1,6,65,2,1,3,2,0,1,1,4,0,0,2,0,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,0,2,0,7,76,2,1,1,0,2,1,2,2,0,1,2,0,68
6603,23,76,0,2,0,8,81,2,1,3,1,0,1,2,2,0,1,2,0,69
6604,20,90,2,1,1,6,65,1,1,3,1,2,1,0,2,0,2,2,0,68
6605,10,86,0,0,1,6,91,0,1,2,1,2,0,2,3,0,1,0,0,68
6606,15,67,2,1,1,9,94,2,1,0,2,2,1,2,4,0,2,2,1,64

In [4]:
X = df.drop(columns=['Exam_Score'],axis =1)
Y = df['Exam_Score']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [10]:
model = DecisionTreeRegressor()
model.fit(X_train,Y_train)
Y_predict = model.predict(X_test)

In [6]:
r2 = r2_score(Y_predict,Y_test)
mse = mean_squared_error(Y_predict,Y_test)
print(r2)
print(mse)

0.548524689709786
4.401387320454959

In [13]:
new = [[19,92,2,2,1,6,65,2,1,3,2,0,1,1,4,0,0,2,0]]
prediction = model.predict(new)
print("Student performance for the given data :",prediction[0])

Student performance for the given data : 70.0

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(