<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 32 - Gender classification

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('gender_classification_v7.csv')

In [3]:
df.isnull().sum()

long_hair                    0
forehead_width_cm            0
forehead_height_cm           0
nose_wide                    0
nose_long                    0
lips_thin                    0
distance_nose_to_lip_long    0
gender                       0
dtype: int64

In [4]:
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

In [5]:
df

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,1
1,0,14.0,5.4,0,0,1,0,0
2,0,11.8,6.3,1,1,1,1,1
3,0,14.4,6.1,0,1,1,1,1
4,1,13.5,5.9,0,0,0,0,0
...,...,...,...,...,...,...,...,...
4996,1,13.6,5.1,0,0,0,0,0
4997,1,11.9,5.4,0,0,0,0,0
4998,1,12.9,5.7,0,0,0,0,0
4999,1,13.2,6.2,0,0,0,0,0
5000,1,15.4,5.4,1,1,1,1,1

In [6]:
X = df.drop(columns='gender',axis=1)
Y = df['gender']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=42)

In [7]:
model = LogisticRegression()
model.fit(X_train,Y_train)
X_train_predict = model.predict(X_train)
print(X_train_predict)

[1 1 1 ... 1 0 1]

In [8]:
accuracy_X = accuracy_score(X_train_predict,Y_train)
print("Accuracy on training data:",accuracy_X)

X_test_predict = model.predict(X_test)
print("Accuracy on test data:",accuracy_score(X_test_predict,Y_test))

Accuracy on training data: 0.97025
Accuracy on test data: 0.964035964035964

In [9]:
input_data = (1,11.8,6.1,1,0,1,1)
input_data_as_num_array = np.asarray(input_data)
input_data_array_reshaped = input_data_as_num_array.reshape(1,-1)
prediction = model.predict(input_data_array_reshaped)

if prediction == 1:
  print("male")
else:
  print("female")

male

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(